# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-16 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='运动英文名称')),
                ('c_name', models.CharField(max_length=50, verbose_name='运动中文名称')),
            ],
            options={
                'verbose_name': '运动项目',
                'verbose_name_plural': '运动项目',
            },
        ),
    ]
