# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-17 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_corpus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='cexing',
            new_name='cixing',
        ),
    ]
