# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-14 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_word', models.CharField(max_length=300, verbose_name='词前')),
                ('word', models.CharField(max_length=300, verbose_name='单词')),
                ('after_word', models.CharField(max_length=300, verbose_name='词前')),
                ('source', models.CharField(default='null', max_length=30, verbose_name='出处')),
                ('meaning', models.CharField(default='null', max_length=30, verbose_name='关键词语义')),
                ('partofspeech', models.CharField(default='null', max_length=30, verbose_name='关键词词性')),
                ('cexing', models.CharField(default='null', max_length=30, verbose_name='层性')),
                ('BCcengxing', models.CharField(default='null', max_length=30, verbose_name='表层层性')),
            ],
            options={
                'verbose_name_plural': '语料库',
                'verbose_name': '语料库',
            },
        ),
    ]
