# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athletes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='昵称')),
                ('birthday', models.DateField(blank=True, default='2010-01-01', null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='女', max_length=6, verbose_name='性别')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
            ],
            options={
                'verbose_name_plural': '运动员',
                'verbose_name': '运动员',
            },
        ),
        migrations.DeleteModel(
            name='Library',
        ),
    ]
