# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-25 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_auto_20180425_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别'),
        ),
    ]
